# Generated by Django 4.0.3 on 2022-06-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('question_cIdentifier', models.CharField(max_length=64)),
                ('question_tIdentifier', models.CharField(max_length=64)),
                ('question_qIdentifier', models.CharField(max_length=64)),
                ('questionName', models.CharField(max_length=200)),
                ('questionLink', models.URLField(max_length=300)),
            ],
        ),
    ]
