# Generated by Django 4.0.5 on 2022-06-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('topic', '0001_initial'),
        ('question', '0003_remove_question_choosecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chooseCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='chooseTopic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='topic.topic'),
            preserve_default=False,
        ),
    ]
