# Generated by Django 4.0.5 on 2022-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
