# Generated by Django 4.0.5 on 2022-06-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_delete_categorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='topic',
            new_name='chooseCategory',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='question',
            new_name='chooseTopic',
        ),
    ]
