# Generated by Django 4.0.5 on 2022-06-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_topic_home_choosecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionName', models.TextField()),
                ('questionView', models.URLField(max_length=300)),
            ],
        ),
    ]
