# Generated by Django 4.0.5 on 2022-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='home',
            name='questionName',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='questionView',
            field=models.URLField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
