# Generated by Django 4.0.5 on 2022-06-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home_questionname_home_questionview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
