# Generated by Django 4.0.3 on 2022-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_topic_topic_cidentifier_topic_topic_tidentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_cIdentifier',
            field=models.CharField(max_length=64),
        ),
    ]
