# Generated by Django 4.0.3 on 2022-07-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question_attempted',
            unique_together={('user', 'attempted_question_qIdentifier')},
        ),
    ]
